// <auto-generated />
using System;
using Garage_2_Group_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2_Group_1.Migrations
{
    [DbContext(typeof(Garage_2_Group_1Context))]
    [Migration("20220128135746_SeedDB")]
    partial class SeedDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_2_Group_1.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WheelCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2022, 1, 28, 14, 57, 45, 860, DateTimeKind.Local).AddTicks(1934),
                            Color = 0,
                            Make = "Toyota",
                            Model = "2H4EZ",
                            RegNr = "ABC123",
                            Type = 0,
                            WheelCount = 4
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2022, 1, 28, 14, 57, 45, 860, DateTimeKind.Local).AddTicks(1966),
                            Color = 0,
                            Make = "Honda",
                            Model = "PCD3Y",
                            RegNr = "ABC12D",
                            Type = 0,
                            WheelCount = 4
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2022, 1, 28, 14, 57, 45, 860, DateTimeKind.Local).AddTicks(1969),
                            Color = 0,
                            Make = "Ford",
                            Model = "68R99",
                            RegNr = "AIR001",
                            Type = 0,
                            WheelCount = 4
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2022, 1, 28, 14, 57, 45, 860, DateTimeKind.Local).AddTicks(1971),
                            Color = 0,
                            Make = "Jeep",
                            Model = "CDOBQ",
                            RegNr = "WET696",
                            Type = 0,
                            WheelCount = 4
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2022, 1, 28, 14, 57, 45, 860, DateTimeKind.Local).AddTicks(1973),
                            Color = 0,
                            Make = "BMW",
                            Model = "GMKJM",
                            RegNr = "BAN420",
                            Type = 0,
                            WheelCount = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
